name: Build Skeleton

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Target tag for re-upload'
        required: true
        default: ''
      version:
        description: 'Which Grav release to use'
        required: true
        default: 'latest'
      admin:
        description: 'Create also a package with Admin'
        required: false
        default: false

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract Tag
        run: echo "SKELETON_VERSION=${{ github.event.inputs.tag || github.ref }}" >> $GITHUB_ENV
      - name: Generate Skeleton Packages
        uses: getgrav/skeleton-builder@v1
        with:
          version: ${{ github.event.inputs.version || 'latest' }}
          admin: ${{ github.event.inputs.admin || false }}
          exclude: README.md
          filename_version: false
      - name: Generate Skeleton Package (Grav 2 Beta)
        run: |
          set -x
          php --version
          mkdir -p /tmp/grav2build && cd /tmp/grav2build
          curl -L https://github.com/getgrav/grav/releases/download/2.0.0-beta.1/grav-v2.0.0-beta.1.zip -o grav.zip
          unzip -q grav.zip && rm grav.zip
          ls -la
          cd grav
          rm -rf user
          cp -Rf $GITHUB_WORKSPACE user
          sudo phpdismod redis && echo "redis disabled"
          ls bin/
          bin/grav install
          sudo chmod -R 777 $GITHUB_WORKSPACE/dist
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | awk -F / '{print $2}')
          zip -x "*.git/*" -x "*.github/workflows/*" -x "*yarn.lock*" -x "*.gitignore*" -x "*.editorconfig*" -x "*.DS_Store*" -x "*hebe.json*" -x "*.dependencies*" -x "*.travis.yml*" -x "README.md" -r "$GITHUB_WORKSPACE/dist/${REPO_NAME}-grav2-beta.zip" .
          ls -la $GITHUB_WORKSPACE/dist/
      - name: Upload packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.SKELETON_VERSION }}
          file: dist/*.zip
          overwrite: true
          file_glob: true
